apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: test/my-app:latest
        imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5000
  selector:
    app: my-app

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: my-app
spec:
  rules:
    - http:
        paths:
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 5678
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 5678
